const articleConstants = {
    FETCH_ARTICLES_STARTED: 'FETCH_ARTICLES_STARTED',
    FETCH_ARTICLES_SUCCEED: 'FETCH_ARTICLES_SUCCEED',
    FETCH_ARTICLES_FAILED: 'FETCH_ARTICLES_FAILED',
    
    FETCH_TRENDING_STARTED: 'FETCH_TRENDING_STARTED',
    FETCH_TRENDING_SUCCEED: 'FETCH_TRENDING_SUCCEED',
    FETCH_TRENDING_FAILED: 'FETCH_TRENDING_FAILED',

    FETCH_ARTICLE_DETAIL_STARTED: 'FETCH_ARTICLE_DETAIL_STARTED',
    FETCH_ARTICLE_DETAIL_SUCCEED: 'FETCH_ARTICLE_DETAIL_SUCCEED',
    FETCH_ARTICLE_DETAIL_FAILED: 'FETCH_ARTICLE_DETAIL_FAILED',

    FETCH_RANDOM_ARTICLES_STARTED: 'FETCH_RANDOM_ARTICLES_STARTED',
    FETCH_RANDOM_ARTICLES_SUCCEED: 'FETCH_RANDOM_ARTICLES_SUCCEED',
    FETCH_RANDOM_ARTICLES_FAILED: 'FETCH_RANDOM_ARTICLES_FAILED',
}

export default articleConstants;