const articleConstants = {
    FETCH_ARTICLES_STARTED: 'FETCH_ARTICLES_STARTED',
    FETCH_ARTICLES_SUCCEED: 'FETCH_ARTICLES_SUCCEED',
    FETCH_ARTICLES_FAILED: 'FETCH_ARTICLES_FAILED',
    
    FETCH_TRENDING_STARTED: 'FETCH_TRENDING_STARTED',
    FETCH_TRENDING_SUCCEED: 'FETCH_TRENDING_SUCCEED',
    FETCH_TRENDING_FAILED: 'FETCH_TRENDING_FAILED',
}

export default articleConstants;