const userConstants = {
    SIGN_IN_STARTED: 'SIGN_IN_STARTED',
    SIGN_IN_SUCCEED: 'SIGN_IN_SUCCEED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',

    FETCH_PROFILE_STARTED: 'FETCH_PROFILE_STARTED',
    FETCH_PROFILE_SUCCEED: 'FETCH_PROFILE_SUCCEED',
    FETCH_PROFILE_FAILED: 'FETCH_PROFILE_FAILED',

    LOGOUT_STARTED: 'LOGOUT_STARTED',
    LOGOUT_SUCCEED: 'LOGOUT_SUCCEED',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    VALIDATE_PHONE_STARTED: 'VALIDATE_PHONE_STARTED',
    VALIDATE_PHONE_SUCCEED: 'VALIDATE_PHONE_SUCCEED',
    VALIDATE_PHONE_FAILED: 'VALIDATE_PHONE_FAILED',

    VALIDATE_OTP_STARTED: 'VALIDATE_OTP_STARTED',
    VALIDATE_OTP_SUCCEED: 'VALIDATE_OTP_SUCCEED',
    VALIDATE_OTP_FAILED: 'VALIDATE_OTP_FAILED',

    SIGN_UP_STARTED: 'SIGN_UP_STARTED',
    SIGN_UP_SUCCEED: 'SIGN_UP_SUCCEED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
};

export default userConstants;